"""Declarative spec tables for the script-command bytecode.

Pure data: command -> argument kinds. Mirrors ``macros/scripts/scripts.asm``
and the related macro definitions; split out from ``scripts.py`` so the
encoder/parser stay readable.
"""

from __future__ import annotations

from .helpers import DATA_BYTE_DIRECTIVES
from .maps import MAP_SECTION_MACROS
from .text import TEXT_COMMAND_SPECS, TEXT_LINE_MACROS, TEXT_TERMINATOR_MACROS


SCRIPT_COMMAND_SPECS: dict[str, tuple[str, ...]] = {
    "scall": ("ptr",),
    "sjump": ("ptr",),
    "iffalse": ("ptr",),
    "iftrue": ("ptr",),
    "ifequal": ("u8", "ptr"),
    "ifnotequal": ("u8", "ptr"),
    "ifgreater": ("u8", "ptr"),
    "ifless": ("u8", "ptr"),
    "memjump": ("ptr",),
    "special": ("special",),
    "checkmapscene": ("map_id",),
    "setmapscene": ("map_id", "u8"),
    "checkscene": (),
    "setscene": ("u8",),
    "setval": ("u8",),
    "addval": ("u8",),
    "random": ("u8",),
    "checkver": (),
    "callasm": ("dba",),
    "readmem": ("ptr",),
    "writemem": ("ptr",),
    "loadvar": ("u8", "u8"),
    "checkitem": ("u8",),
    "giveitem": ("u8", "u8_default_1"),
    "takeitem": ("u8", "u8_default_1"),
    "givemoney": ("u8", "money24"),
    "takemoney": ("u8", "money24"),
    "checkmoney": ("u8", "money24"),
    "givecoins": ("u16",),
    "takecoins": ("u16",),
    "checkcoins": ("u16",),
    "checkevent": ("u16",),
    "clearevent": ("u16",),
    "setevent": ("u16",),
    "checkflag": ("u16",),
    "clearflag": ("u16",),
    "setflag": ("u16",),
    "xycompare": ("ptr",),
    "warpmod": ("u8", "map_id"),
    "blackoutmod": ("map_id",),
    "warp": ("map_id", "u8", "u8"),
    "loadmem": ("ptr", "u8"),
    "readvar": ("u8",),
    "writevar": ("u8",),
    "addcellnum": ("u8",),
    "givepoke": ("givepoke",),
    "giveegg": ("u8", "u8"),
    "givepokemail": ("ptr",),
    "checkpokemail": ("ptr",),
    "getitemname": ("u8_arg_2", "u8_arg_1"),
    "gettrainername": ("trainername",),
    "getmoney": ("u8_arg_2", "u8_arg_1"),
    "getcoins": ("u8",),
    "getnum": ("u8",),
    "getmonname": ("u8_arg_2", "u8_arg_1"),
    "getcurlandmarkname": ("u8",),
    "getstring": ("ptr_arg_2", "u8_arg_1"),
    "itemnotify": (),
    "pocketisfull": (),
    "opentext": (),
    "reanchormap": ("u8_default_0",),
    "closetext": (),
    "writetext": ("ptr",),
    "yesorno": (),
    "loadmenu": ("ptr",),
    "closewindow": (),
    "pokepic": ("u8",),
    "closepokepic": (),
    "_2dmenu": (),
    "jumptextfaceplayer": ("ptr",),
    "jumptext": ("ptr",),
    "waitbutton": (),
    "promptbutton": (),
    "applymovement": ("u8", "ptr"),
    "applymovementlasttalked": ("ptr",),
    "faceplayer": (),
    "setlasttalked": ("u8",),
    "showemote": ("u8", "u8", "u8"),
    "turnobject": ("u8", "u8"),
    "faceobject": ("u8", "u8"),
    "variablesprite": ("u8_minus_sprite_vars", "u8"),
    "appear": ("u8",),
    "disappear": ("u8",),
    "follow": ("u8", "u8"),
    "stopfollow": (),
    "moveobject": ("u8", "u8", "u8"),
    "writeobjectxy": ("u8",),
    "loademote": ("u8",),
    "follownotexact": ("u8", "u8"),
    "verticalmenu": (),
    "loadtrainer": ("u8", "u8"),
    "startbattle": (),
    "reloadmapafterbattle": (),
    "scripttalkafter": (),
    "endifjustbattled": (),
    "checkjustbattled": (),
    "winlosstext": ("ptr", "ptr"),
    "earthquake": ("u8",),
    "changeblock": ("u8", "u8", "u8"),
    "reloadmap": (),
    "refreshmap": (),
    "delcmdqueue": ("u8",),
    "writecmdqueue": ("ptr",),
    "loadwildmon": ("u8", "u8"),
    "loadtemptrainer": ("u8", "u8"),
    "randomwildmon": (),
    "catchtutorial": ("u8",),
    "newloadmap": ("u8",),
    "cry": ("u16",),
    "playmusic": ("u16",),
    "musicfadeout": ("u16", "u8"),
    "playmapmusic": (),
    "dontrestartmapmusic": (),
    "pause": ("u8",),
    "playsound": ("u16",),
    "waitsfx": (),
    "warpsound": (),
    "specialsound": (),
    "autoinput": ("dba",),
    "jumpstd": ("stdscript",),
    "callstd": ("stdscript",),
    "endcallback": (),
    "end": (),
    "reloadend": ("u8",),
    "endall": (),
    "verbosegiveitem": ("u8", "u8_default_1"),
    "pokemart": ("u8", "u16"),
    "elevator": ("ptr",),
    "trade": ("u8",),
    "askforphonenumber": ("u8",),
    "phonecall": ("ptr",),
    "hangup": (),
    "describedecoration": ("u8",),
    "fruittree": ("u8",),
    "specialphonecall": ("u16",),
    "checkphonecall": (),
    "swarm": ("map_id",),
    "halloffame": (),
    "credits": (),
    "sdefer": ("ptr",),
    "warpcheck": (),
    "stopandsjump": ("ptr",),
}
SCRIPT_DATA_MACRO_SPECS: dict[str, tuple[str, ...]] = {
    "cmdqueue": (),
    "stonetable": (),
    "trainer": (),
    "doorstate": (),
}
SCRIPT_TERMINAL_COMMANDS = {"sjump", "jumpstd", "jumptext", "jumptextfaceplayer", "end", "endcallback", "endall"}

NON_SCRIPT_BLOCK_START_TOKENS = (
    DATA_BYTE_DIRECTIVES
    | set(MAP_SECTION_MACROS)
    | set(MAP_SECTION_MACROS.values())
    | set(TEXT_LINE_MACROS)
    | set(TEXT_TERMINATOR_MACROS)
    | set(TEXT_COMMAND_SPECS)
    | {
        "INCBIN",
        "MACRO",
        "ENDM",
        "SECTION",
        "rept",
        "endr",
        "object_const_def",
        "def_scene_scripts",
        "scene_script",
        "def_callbacks",
        "callback",
        "conditional_event",
        "itemball",
        "hiddenitem",
        "tmhm",
        "dbw",
        "bigdw",
        "bigdt",
        "farcall",
        "call",
        "ret",
        "reti",
        "jp",
        "jr",
        "ld",
        "ldi",
        "ldd",
        "cp",
        "inc",
        "dec",
        "push",
        "pop",
        "xor",
        "and",
        "or",
        "add",
        "adc",
        "sub",
        "sbc",
        "rst",
        "bit",
        "set",
        "res",
    }
)
