; ============================================================
; data/boss_ai/matchup_tables.asm — Per-leader type matchup tables
;
; GENERATED by scripts/generate_boss_matchup_tables.py. Do not hand-edit;
; rerun the generator after any change to parties.asm, base_stats/*.asm,
; moves.asm, or type_matchups.asm.
;
; ABI (consumer-facing): see the script header for full byte layout.
; Brief: each leader row is `db <class>, <id>, <party_count>` followed by
; per-slot blocks. Each slot is `db <species>` + 17 defensive bytes + 17
; offensive bytes (canonical type order: NORMAL, FIGHTING, FLYING, POISON,
; GROUND, ROCK, BUG, GHOST, STEEL, FIRE, WATER, GRASS, ELECTRIC,
; PSYCHIC_TYPE, ICE, DRAGON, DARK). Multiplier bytes are raw matchup
; loop values: 0 = NO_EFFECT, 5 = NOT_VERY_EFFECTIVE, 10 = NORMAL,
; 20 = SUPER_EFFECTIVE.
;
; Table is terminated by a single `db 0` (trainer class 0 = sentinel).
; ============================================================

BossAIMatchupTables::
	; MORTY : MORTY1
	db MORTY, MORTY1
	db 4
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10 ; offensive vector
	db MISDREAVUS
	db 0, 0, 10, 5, 0, 10, 5, 20, 10, 10, 10, 10, 10, 10, 10, 10, 20 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 20, 20, 10, 20, 10, 20, 10 ; offensive vector

	; PRYCE : PRYCE1
	db PRYCE, PRYCE1
	db 5
	db CLOYSTER
	db 10, 20, 10, 10, 10, 20, 10, 10, 10, 10, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 20, 20, 10, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10 ; offensive vector
	db DEWGONG
	db 10, 20, 10, 10, 10, 20, 10, 10, 10, 10, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10, 20, 10 ; offensive vector
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db PILOSWINE
	db 10, 20, 10, 5, 10, 10, 10, 10, 20, 20, 10, 20, 0, 10, 10, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 20, 20, 20, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10 ; offensive vector
	db SLOWKING
	db 5, 5, 10, 10, 10, 5, 20, 20, 5, 5, 5, 20, 20, 5, 5, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 20, 10, 10, 10, 20, 20, 10, 10, 10, 10, 10, 10 ; offensive vector

	; JASMINE : JASMINE1
	db JASMINE, JASMINE1
	db 5
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 10, 10, 20, 10, 20, 10, 20, 10, 10, 10, 10 ; offensive vector
	db FORRETRESS
	db 5, 20, 10, 0, 10, 10, 5, 0, 5, 20, 10, 5, 10, 5, 5, 5, 10 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db SCIZOR
	db 5, 20, 10, 0, 10, 10, 5, 0, 5, 20, 10, 5, 10, 5, 5, 5, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 20, 20, 10, 5, 10, 10, 20, 10, 10, 20, 10, 10 ; offensive vector
	db STEELIX
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 10, 5, 5, 5, 5, 10, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 10 ; offensive vector
	db SKARMORY
	db 5, 10, 5, 0, 0, 10, 5, 0, 5, 20, 10, 5, 20, 5, 10, 5, 10 ; defensive vector
	db 20, 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 20, 20, 10, 20, 10, 10 ; offensive vector

	; CHUCK : CHUCK1
	db CHUCK, CHUCK1
	db 5
	db SUDOWOODO
	db 5, 20, 5, 5, 20, 10, 10, 10, 20, 5, 20, 20, 10, 10, 10, 10, 10 ; defensive vector
	db 20, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 20 ; offensive vector
	db HITMONTOP
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 10, 20, 20, 10, 20, 20, 10, 10, 10, 5, 20, 10, 20 ; offensive vector
	db HITMONLEE
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 10, 20, 20, 10, 20, 20, 10, 10, 10, 5, 20, 10, 20 ; offensive vector
	db UMBREON
	db 10, 20, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db POLIWRATH
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 5, 5, 20, 20, 20, 5, 10, 5 ; defensive vector
	db 20, 20, 20, 10, 20, 20, 10, 10, 20, 20, 10, 20, 10, 10, 20, 20, 20 ; offensive vector

	; CLAIR : CLAIR1
	db CLAIR, CLAIR1
	db 6
	db GLIGAR
	db 10, 5, 10, 5, 0, 10, 5, 10, 10, 10, 20, 20, 0, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 20, 10, 20, 20, 10, 20, 10, 10, 20, 20, 10, 10, 10, 10 ; offensive vector
	db MANTINE
	db 10, 5, 10, 10, 0, 20, 5, 10, 5, 5, 5, 20, 20, 10, 10, 10, 10 ; defensive vector
	db 10, 20, 20, 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db KINGDRA
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 10, 10, 10, 10, 20, 10 ; defensive vector
	db 10, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10, 20, 10 ; offensive vector
	db DRAGONAIR
	db 10, 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 5, 10, 20, 20, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db STEELIX
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 10, 5, 5, 5, 5, 10, 10, 10 ; defensive vector
	db 10, 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 20, 10 ; offensive vector
	db DRAGONAIR
	db 10, 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 5, 10, 20, 20, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 20, 10, 20, 20, 10, 20, 10, 10, 20, 20, 10 ; offensive vector

	; RIVAL1 : RIVAL1_1_CHIKORITA
	db RIVAL1, RIVAL1_1_CHIKORITA
	db 1
	db CHIKORITA
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 5, 10, 0, 5, 10, 10, 10, 10, 5, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_1_CYNDAQUIL
	db RIVAL1, RIVAL1_1_CYNDAQUIL
	db 1
	db CYNDAQUIL
	db 10, 10, 10, 10, 10, 20, 5, 10, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 5, 10, 0, 5, 10, 10, 10, 10, 5, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_1_TOTODILE
	db RIVAL1, RIVAL1_1_TOTODILE
	db 1
	db TOTODILE
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 5, 10, 0, 5, 10, 10, 10, 10, 5, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_2_CHIKORITA
	db RIVAL1, RIVAL1_2_CHIKORITA
	db 3
	db GASTLY
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db BAYLEEF
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 20, 20, 10, 10, 5, 10, 20, 20, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_2_CYNDAQUIL
	db RIVAL1, RIVAL1_2_CYNDAQUIL
	db 3
	db GASTLY
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db QUILAVA
	db 10, 10, 10, 10, 10, 20, 5, 10, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_2_TOTODILE
	db RIVAL1, RIVAL1_2_TOTODILE
	db 3
	db GASTLY
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db CROCONAW
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 20, 10, 20, 10, 10, 10, 20, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_3_CHIKORITA
	db RIVAL1, RIVAL1_3_CHIKORITA
	db 4
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db BAYLEEF
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 20, 20, 10, 10, 5, 10, 20, 20, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_3_CYNDAQUIL
	db RIVAL1, RIVAL1_3_CYNDAQUIL
	db 4
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db QUILAVA
	db 10, 10, 10, 10, 10, 20, 5, 10, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_3_TOTODILE
	db RIVAL1, RIVAL1_3_TOTODILE
	db 4
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector
	db CROCONAW
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 20, 10, 20, 10, 10, 10, 20, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_4_CHIKORITA
	db RIVAL1, RIVAL1_4_CHIKORITA
	db 5
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20 ; offensive vector
	db GOLBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db MEGANIUM
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 20, 20, 10, 10, 5, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_4_CYNDAQUIL
	db RIVAL1, RIVAL1_4_CYNDAQUIL
	db 5
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20 ; offensive vector
	db GOLBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db QUILAVA
	db 10, 10, 10, 10, 10, 20, 5, 10, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_4_TOTODILE
	db RIVAL1, RIVAL1_4_TOTODILE
	db 5
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20 ; offensive vector
	db GOLBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNEMITE
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db HAUNTER
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; offensive vector
	db FERALIGATR
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 5, 5, 20, 20, 20, 5, 10, 5 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 20, 10, 20, 10, 10, 10, 20, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_5_CHIKORITA
	db RIVAL1, RIVAL1_5_CHIKORITA
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 20, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 20, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 20, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db MEGANIUM
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_5_CYNDAQUIL
	db RIVAL1, RIVAL1_5_CYNDAQUIL
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 20, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 20, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 20, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db TYPHLOSION
	db 10, 20, 10, 20, 10, 20, 5, 0, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 20, 20, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL1 : RIVAL1_5_TOTODILE
	db RIVAL1, RIVAL1_5_TOTODILE
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 20, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 20, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 20, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db FERALIGATR
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 5, 5, 20, 20, 20, 5, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 20, 20, 10, 10, 20, 20, 10, 10, 10, 10, 20, 20, 20 ; offensive vector

	; WILL : WILL1
	db WILL, WILL1
	db 6
	db FORRETRESS
	db 5, 20, 10, 0, 10, 10, 5, 0, 5, 20, 10, 5, 10, 5, 5, 5, 10 ; defensive vector
	db 20, 10, 10, 20, 10, 20, 10, 5, 20, 10, 10, 20, 20, 10, 10, 10, 10 ; offensive vector
	db STARMIE
	db 5, 5, 10, 10, 10, 5, 20, 20, 5, 5, 5, 20, 20, 5, 5, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 20, 10, 10, 10, 20, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db SLOWBRO
	db 5, 5, 10, 10, 10, 5, 20, 20, 5, 5, 5, 20, 20, 5, 5, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 20, 20, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db HOUNDOOM
	db 10, 20, 10, 10, 10, 20, 10, 5, 5, 5, 20, 5, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 20, 20, 20, 10, 10, 20, 10, 20, 20, 10, 10 ; offensive vector
	db XATU
	db 5, 5, 10, 10, 0, 10, 10, 20, 10, 10, 10, 10, 20, 5, 20, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 20, 20, 5, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector

	; BRUNO : BRUNO1
	db BRUNO, BRUNO1
	db 6
	db ONIX
	db 5, 20, 5, 5, 20, 5, 10, 10, 20, 5, 20, 20, 0, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 10 ; offensive vector
	db HITMONTOP
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 10, 20, 20, 10, 20, 20, 10, 10, 10, 5, 20, 10, 20 ; offensive vector
	db HITMONLEE
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 20, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 20 ; offensive vector
	db MACHAMP
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 20 ; offensive vector
	db HITMONCHAN
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 10, 10, 10, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 20, 20, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 20 ; offensive vector
	db HERACROSS
	db 10, 10, 20, 10, 5, 10, 5, 20, 5, 20, 10, 5, 10, 20, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 10, 20, 20, 10, 20, 20, 10, 20, 10, 20, 20, 10, 20 ; offensive vector

	; KAREN : KAREN1
	db KAREN, KAREN1
	db 6
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 10, 20, 20, 10, 10, 10 ; offensive vector
	db DONPHAN
	db 10, 10, 10, 5, 10, 5, 10, 10, 10, 10, 20, 20, 0, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 10 ; offensive vector
	db MURKROW
	db 10, 10, 10, 10, 0, 20, 10, 5, 10, 10, 10, 10, 20, 0, 20, 10, 5 ; defensive vector
	db 10, 20, 10, 10, 10, 20, 20, 20, 10, 10, 10, 20, 10, 20, 20, 10, 10 ; offensive vector
	db TYRANITAR
	db 5, 20, 5, 5, 20, 10, 20, 5, 20, 5, 20, 20, 10, 0, 10, 10, 5 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 20, 20, 20, 10, 10, 20, 20, 20, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 5, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db HOUNDOOM
	db 10, 20, 10, 10, 10, 20, 10, 5, 5, 5, 20, 5, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 20, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10 ; offensive vector

	; KOGA : KOGA1
	db KOGA, KOGA1
	db 6
	db ARIADOS
	db 10, 10, 20, 5, 10, 20, 5, 10, 10, 20, 10, 5, 10, 10, 10, 10, 10 ; defensive vector
	db 20, 10, 10, 20, 10, 20, 10, 5, 20, 10, 10, 20, 20, 20, 10, 10, 20 ; offensive vector
	db TENTACRUEL
	db 10, 10, 10, 5, 20, 10, 5, 10, 5, 5, 5, 10, 20, 10, 5, 10, 10 ; defensive vector
	db 20, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10, 20, 10 ; offensive vector
	db MUK
	db 10, 10, 10, 5, 20, 10, 5, 10, 10, 10, 10, 5, 10, 10, 10, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db NIDOKING
	db 10, 10, 10, 5, 20, 5, 5, 10, 10, 10, 20, 10, 0, 10, 20, 10, 10 ; defensive vector
	db 20, 10, 20, 20, 20, 20, 10, 10, 20, 10, 20, 20, 20, 10, 10, 20, 10 ; offensive vector
	db UMBREON
	db 10, 20, 10, 10, 10, 10, 20, 5, 10, 10, 10, 10, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 5, 20, 10, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector

	; CHAMPION : LANCE
	db CHAMPION, LANCE
	db 6
	db STEELIX
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 10, 5, 5, 5, 5, 10, 10, 10 ; defensive vector
	db 10, 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 20, 10 ; offensive vector
	db GYARADOS
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 10, 10, 10, 10, 20, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 10, 10, 10, 10, 20, 10 ; offensive vector
	db AMPHAROS
	db 10, 10, 5, 10, 20, 10, 10, 10, 10, 5, 5, 5, 5, 10, 20, 20, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db YANMA
	db 10, 10, 20, 10, 5, 20, 10, 10, 10, 10, 5, 5, 5, 10, 20, 20, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 20, 10, 20, 10, 20, 20 ; offensive vector
	db KINGDRA
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 10, 10, 10, 10, 20, 10 ; defensive vector
	db 10, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10, 20, 10 ; offensive vector
	db DRAGONITE
	db 10, 5, 10, 10, 0, 20, 5, 10, 10, 5, 5, 5, 10, 10, 20, 20, 10 ; defensive vector
	db 10, 10, 10, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 10, 20, 10 ; offensive vector

	; RIVAL2 : RIVAL2_1_CHIKORITA
	db RIVAL2, RIVAL2_1_CHIKORITA
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db MEGANIUM
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL2 : RIVAL2_1_CYNDAQUIL
	db RIVAL2, RIVAL2_1_CYNDAQUIL
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db TYPHLOSION
	db 10, 20, 10, 20, 10, 20, 5, 0, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 20, 20, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL2 : RIVAL2_1_TOTODILE
	db RIVAL2, RIVAL2_1_TOTODILE
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db FERALIGATR
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 5, 5, 20, 20, 20, 5, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 20, 20, 10, 10, 20, 20, 10, 10, 10, 10, 20, 20, 20 ; offensive vector

	; RIVAL2 : RIVAL2_2_CHIKORITA
	db RIVAL2, RIVAL2_2_CHIKORITA
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db MEGANIUM
	db 10, 10, 20, 20, 5, 10, 20, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector

	; RIVAL2 : RIVAL2_2_CYNDAQUIL
	db RIVAL2, RIVAL2_2_CYNDAQUIL
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db TYPHLOSION
	db 10, 20, 10, 20, 10, 20, 5, 0, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10 ; offensive vector

	; RIVAL2 : RIVAL2_2_TOTODILE
	db RIVAL2, RIVAL2_2_TOTODILE
	db 6
	db SNEASEL
	db 10, 20, 10, 10, 10, 20, 20, 5, 20, 20, 5, 10, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector
	db CROBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 20, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db MAGNETON
	db 5, 20, 5, 0, 20, 5, 5, 0, 5, 20, 10, 5, 5, 5, 5, 5, 10 ; defensive vector
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db GENGAR
	db 0, 0, 10, 5, 0, 5, 10, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 10, 10, 10, 20, 10, 10, 20, 10, 10, 20, 10, 10, 10 ; offensive vector
	db ALAKAZAM
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 10, 20, 10, 20, 20, 10, 10, 20, 20, 10 ; offensive vector
	db FERALIGATR
	db 10, 10, 20, 10, 10, 5, 5, 20, 5, 5, 5, 20, 20, 20, 5, 10, 5 ; defensive vector
	db 20, 10, 10, 20, 20, 20, 10, 10, 20, 20, 10, 10, 20, 10, 20, 20, 20 ; offensive vector

	; EXECUTIVEM : EXECUTIVEM_1
	db EXECUTIVEM, EXECUTIVEM_1
	db 3
	db HOUNDOUR
	db 10, 20, 10, 10, 10, 20, 10, 5, 5, 5, 20, 5, 10, 0, 5, 10, 5 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 20, 20, 20, 10, 10, 20, 10, 20, 20, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 20, 10, 20, 10, 10, 10, 5, 10, 10, 20, 10, 10, 10, 20, 10 ; offensive vector
	db HOUNDOOM
	db 10, 20, 10, 10, 10, 20, 10, 5, 5, 5, 20, 5, 10, 0, 5, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 10, 20, 20, 20, 10, 10, 20, 10, 20, 20, 10, 10 ; offensive vector

	; EXECUTIVEM : EXECUTIVEM_2
	db EXECUTIVEM, EXECUTIVEM_2
	db 1
	db GOLBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 10, 20 ; offensive vector

	; EXECUTIVEM : EXECUTIVEM_3
	db EXECUTIVEM, EXECUTIVEM_3
	db 6
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db WEEZING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 5, 10, 5, 5, 10, 10, 20, 10, 10, 10, 10, 10 ; offensive vector

	; EXECUTIVEM : EXECUTIVEM_4
	db EXECUTIVEM, EXECUTIVEM_4
	db 3
	db ZUBAT
	db 10, 5, 10, 5, 0, 20, 5, 10, 10, 10, 10, 5, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; offensive vector
	db RATICATE
	db 10, 20, 10, 20, 10, 10, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; offensive vector
	db KOFFING
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; offensive vector

	; EXECUTIVEF : EXECUTIVEF_1
	db EXECUTIVEF, EXECUTIVEF_1
	db 3
	db ARBOK
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db VILEPLUME
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 20, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 20, 10, 10, 10, 10, 10 ; offensive vector
	db MURKROW
	db 10, 10, 10, 10, 0, 20, 10, 5, 10, 10, 10, 10, 20, 0, 20, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector

	; EXECUTIVEF : EXECUTIVEF_2
	db EXECUTIVEF, EXECUTIVEF_2
	db 3
	db ARBOK
	db 10, 20, 10, 5, 20, 10, 10, 5, 10, 10, 10, 5, 10, 0, 10, 10, 5 ; defensive vector
	db 20, 10, 10, 10, 10, 10, 10, 20, 10, 10, 10, 20, 10, 20, 10, 10, 10 ; offensive vector
	db GLOOM
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 20, 10, 10, 10, 20, 20, 10, 10, 5, 10, 20, 20, 10, 10, 10, 10, 10 ; offensive vector
	db MURKROW
	db 10, 10, 10, 10, 0, 20, 10, 5, 10, 10, 10, 10, 20, 0, 20, 10, 5 ; defensive vector
	db 10, 20, 20, 10, 20, 10, 20, 20, 10, 10, 10, 20, 10, 20, 10, 20, 10 ; offensive vector

	; RED : RED1
	db RED, RED1
	db 6
	db PIKACHU
	db 10, 10, 5, 10, 20, 10, 10, 10, 10, 10, 10, 10, 5, 10, 10, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 20, 20, 10, 10, 10, 20, 20, 10, 10, 10, 10, 10, 10 ; offensive vector
	db ESPEON
	db 5, 5, 10, 10, 10, 5, 20, 20, 10, 10, 10, 10, 10, 5, 10, 10, 20 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 10, 5, 10, 10, 10, 10, 5, 10, 10, 10 ; offensive vector
	db SNORLAX
	db 10, 20, 10, 20, 10, 10, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; offensive vector
	db VENUSAUR
	db 10, 10, 20, 10, 10, 10, 10, 10, 10, 20, 5, 5, 5, 10, 20, 10, 10 ; defensive vector
	db 20, 10, 10, 10, 20, 20, 20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10 ; offensive vector
	db CHARIZARD
	db 10, 5, 10, 10, 0, 20, 5, 10, 5, 5, 20, 5, 20, 10, 10, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 20, 20, 20, 10, 20, 10, 20, 20, 10, 10, 20, 10, 10 ; offensive vector
	db BLASTOISE
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 20, 20, 10, 5, 10, 10 ; defensive vector
	db 10, 20, 20, 20, 20, 20, 10, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10 ; offensive vector

	; BLUE : BLUE1
	db BLUE, BLUE1
	db 6
	db PIDGEOT
	db 10, 10, 10, 20, 0, 20, 5, 0, 10, 10, 10, 10, 20, 10, 20, 10, 10 ; defensive vector
	db 10, 20, 10, 10, 10, 20, 20, 10, 5, 10, 10, 20, 10, 10, 20, 10, 10 ; offensive vector
	db PORYGON2
	db 10, 20, 10, 20, 10, 10, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; defensive vector
	db 10, 10, 20, 10, 20, 10, 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10 ; offensive vector
	db GYARADOS
	db 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 10, 10, 10, 10, 20, 10 ; defensive vector
	db 10, 10, 10, 10, 20, 20, 10, 10, 10, 20, 10, 10, 10, 10, 10, 20, 10 ; offensive vector
	db TAUROS
	db 10, 20, 10, 20, 10, 10, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 10, 20, 10, 20, 10, 10 ; offensive vector
	db RHYDON
	db 5, 20, 5, 5, 20, 5, 10, 10, 20, 5, 20, 20, 0, 10, 20, 10, 10 ; defensive vector
	db 10, 10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 20, 20, 20, 20, 10, 20 ; offensive vector
	db ARCANINE
	db 10, 10, 10, 10, 10, 20, 5, 10, 5, 5, 20, 5, 10, 10, 5, 10, 10 ; defensive vector
	db 10, 10, 10, 10, 10, 10, 20, 20, 20, 10, 10, 20, 10, 20, 20, 20, 10 ; offensive vector

	db 0 ; end-of-table sentinel
