"""Caller-owned exchange/matrix layout; mirrors action_value/joint_action.asm."""
AD_SIZE = 51
AV_SIZE = 89
AV_PREPARED_DAMAGE = AV_SIZE + AD_SIZE
AV_PREPARED_SIZE = AV_PREPARED_DAMAGE + 1 + AD_SIZE + 1 + AD_SIZE + 8 + 3 * 13 + 1 + 2 * 16
JC_SCORES = AV_PREPARED_SIZE + 8 + 67
JC_TOTAL = JC_SCORES + 42
JC_MASS = JC_TOTAL + 5
JC_OWN_ACCURACY = JC_MASS + 3
JC_REPLY_ACCURACY = JC_OWN_ACCURACY + 1
JC_BEST_INDEX = JC_REPLY_ACCURACY + 5
JC_SIZE = JC_BEST_INDEX + 2
