#!/usr/bin/env python3
"""Emit a normalized BGB/Emulicious-compatible symbol file from RGBDS .sym."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


ROOT = Path(__file__).resolve().parents[1]
SYMBOL_RE = re.compile(r"^\s*(?P<bank>[0-9A-Fa-f]{2}):(?P<address>[0-9A-Fa-f]{4})\s+(?P<label>\S+)\s*$")


@dataclass(frozen=True)
class Symbol:
    bank: int
    address: int
    label: str
    line_no: int

    @property
    def key(self) -> tuple[str, int, int]:
        return (self.label, self.bank, self.address)

    def bgb_line(self) -> str:
        return f"{self.bank:02X}:{self.address:04X} {self.label}"


def parse_symbol_lines(lines: Iterable[str]) -> list[Symbol]:
    symbols: list[Symbol] = []
    for line_no, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        match = SYMBOL_RE.match(line)
        if not match:
            continue
        symbols.append(
            Symbol(
                bank=int(match.group("bank"), 16),
                address=int(match.group("address"), 16),
                label=match.group("label"),
                line_no=line_no,
            )
        )
    return symbols


def parse_symbol_file(path: Path) -> list[Symbol]:
    return parse_symbol_lines(path.read_text(encoding="utf-8", errors="replace").splitlines())


def emit_bgb_sym(symbols: Iterable[Symbol]) -> str:
    lines = ["; File generated by scripts/emit_bgb_sym.py"]
    lines.extend(symbol.bgb_line() for symbol in symbols)
    return "\n".join(lines) + "\n"


def write_bgb_sym(*, symbols_path: Path, out_path: Path) -> dict[str, object]:
    symbols = parse_symbol_file(symbols_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(emit_bgb_sym(symbols), encoding="utf-8", newline="\n")
    return {
        "ok": True,
        "symbols": str(symbols_path),
        "out": str(out_path),
        "symbol_count": len(symbols),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Normalize an RGBDS .sym file for BGB/Emulicious/SameBoy loading."
    )
    parser.add_argument("--symbols", default="pokegold.sym", help="input RGBDS .sym path")
    parser.add_argument("--out", default="pokegold.bgb.sym", help="output BGB-compatible .sym path")
    parser.add_argument("--json", action="store_true", help="emit machine-readable summary")
    args = parser.parse_args(list(argv) if argv is not None else None)

    symbols_path = (ROOT / args.symbols).resolve() if not Path(args.symbols).is_absolute() else Path(args.symbols)
    out_path = (ROOT / args.out).resolve() if not Path(args.out).is_absolute() else Path(args.out)
    if not symbols_path.exists():
        print(f"FAIL: missing symbol file: {symbols_path}")
        return 1
    report = write_bgb_sym(symbols_path=symbols_path, out_path=out_path)
    if args.json:
        print(json.dumps(report, sort_keys=True))
    else:
        print(f"wrote {report['symbol_count']} symbols to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
