#!/usr/bin/env python3
"""Emit a compact SRAM/WRAM/HRAM label table from an RGBDS .sym file."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Sequence

try:
    from scripts.emit_bgb_sym import Symbol, parse_symbol_file
except ModuleNotFoundError:  # direct script execution
    from emit_bgb_sym import Symbol, parse_symbol_file


ROOT = Path(__file__).resolve().parents[1]
REGION_ORDER = {"SRAM": 0, "WRAM": 1, "HRAM": 2}


def memory_region(symbol: Symbol) -> str:
    if 0xA000 <= symbol.address <= 0xBFFF:
        return "SRAM"
    if 0xC000 <= symbol.address <= 0xDFFF:
        return "WRAM"
    if 0xFF80 <= symbol.address <= 0xFFFF:
        return "HRAM"
    return ""


def emit_wram_map(symbols: list[Symbol]) -> str:
    rows: list[tuple[str, int, int, str]] = []
    for symbol in symbols:
        region = memory_region(symbol)
        if region:
            rows.append((region, symbol.bank, symbol.address, symbol.label))
    rows.sort(key=lambda row: (REGION_ORDER[row[0]], row[1], row[2], row[3]))
    lines = [
        "# File generated by scripts/emit_wram_map.py",
        "# region bank address label",
    ]
    lines.extend(f"{region} {bank:02X} {address:04X} {label}" for region, bank, address, label in rows)
    return "\n".join(lines) + "\n"


def write_wram_map(*, symbols_path: Path, out_path: Path) -> dict[str, object]:
    symbols = parse_symbol_file(symbols_path)
    rows = [symbol for symbol in symbols if memory_region(symbol)]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(emit_wram_map(symbols), encoding="utf-8", newline="\n")
    return {
        "ok": True,
        "symbols": str(symbols_path),
        "out": str(out_path),
        "label_count": len(rows),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Emit a SRAM/WRAM/HRAM label table from an RGBDS .sym file."
    )
    parser.add_argument("--symbols", default="pokegold.sym", help="input RGBDS .sym path")
    parser.add_argument("--out", default="pokegold.map.txt", help="output SRAM/WRAM/HRAM map path")
    parser.add_argument("--json", action="store_true", help="emit machine-readable summary")
    args = parser.parse_args(list(argv) if argv is not None else None)

    symbols_path = (ROOT / args.symbols).resolve() if not Path(args.symbols).is_absolute() else Path(args.symbols)
    out_path = (ROOT / args.out).resolve() if not Path(args.out).is_absolute() else Path(args.out)
    if not symbols_path.exists():
        print(f"FAIL: missing symbol file: {symbols_path}")
        return 1
    report = write_wram_map(symbols_path=symbols_path, out_path=out_path)
    if args.json:
        print(json.dumps(report, sort_keys=True))
    else:
        print(f"wrote {report['label_count']} SRAM/WRAM/HRAM labels to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
