#!/usr/bin/env python3
"""Generate engine/battle/ai/fast_contact_flags.inc from data/moves/contact_flags.asm.

The offline AI reference build (BOSS_AI_REFERENCE) keeps an in-bank mirror of
the moves table and folds each move's contact flag into bit 7 of the mirror's
type byte (see the mirror macro in data/moves/contact_flags.asm's consumer,
data/moves/moves.asm). RGBDS cannot read back `db` values at assembly time, so
the flags are restated here as `DEF fast_contact_N EQU TRUE|FALSE`, one per
move id, generated from the authoritative table. `--check` exits 1 when the
committed file differs from what the table says (tools/audit/check_fast_contact_flags.py).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "moves" / "contact_flags.asm"
OUTPUT = ROOT / "engine" / "battle" / "ai" / "fast_contact_flags.inc"
ROW = re.compile(r"^\s*db\s+(TRUE|FALSE)\s*;\s*([A-Z0-9_]+)\s*$", re.M)


def render() -> str:
    rows = ROW.findall(SOURCE.read_text(encoding="utf-8"))
    if not rows:
        raise SystemExit(f"no contact flag rows found in {SOURCE}")
    lines = [
        "; Generated by scripts/generate_fast_contact_flags.py from",
        "; data/moves/contact_flags.asm; do not edit. fast_contact_N is move N's",
        "; contact flag; the offline AI reference's moves mirror folds it into bit 7",
        "; of the type byte (data/moves/moves.asm). Audited by",
        "; tools/audit/check_fast_contact_flags.py.",
        "",
    ]
    for index, (flag, name) in enumerate(rows, 1):
        lines.append(f"DEF fast_contact_{index} EQU {flag} ; {name}")
    lines.append(f"DEF FAST_CONTACT_COUNT EQU {len(rows)}")
    lines.append("ASSERT FAST_CONTACT_COUNT == NUM_ATTACKS")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare the committed file with the table instead of writing")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"FAIL: {OUTPUT.relative_to(ROOT)} differs from {SOURCE.relative_to(ROOT)}; run scripts/generate_fast_contact_flags.py")
            return 1
        print(f"PASS: {OUTPUT.relative_to(ROOT)} matches {SOURCE.relative_to(ROOT)} ({text.count('DEF fast_contact_')} moves)")
        return 0
    OUTPUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
