from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from scripts.emit_bgb_sym import emit_bgb_sym, parse_symbol_file, write_bgb_sym
from scripts.emit_wram_map import emit_wram_map
from tools.audit.check_bgb_sym_parity import build_parity_report


class BgbSymParityTests(unittest.TestCase):
    def test_bgb_sym_export_normalizes_rgbds_symbols(self) -> None:
        symbols = _write_symbols(
            "01:d141 wCurDamage\n"
            "03:4000 BattleCommand_DamageCalc\n"
        )
        parsed = parse_symbol_file(symbols)

        text = emit_bgb_sym(parsed)

        self.assertIn("01:D141 wCurDamage", text)
        self.assertIn("03:4000 BattleCommand_DamageCalc", text)

    def test_wram_map_emits_only_sram_wram_hram_labels(self) -> None:
        symbols = parse_symbol_file(
            _write_symbols(
                "00:a600 sPartyMail\n"
                "01:d141 wCurDamage\n"
                "00:ff9f hROMBank\n"
                "03:4000 BattleCommand_DamageCalc\n"
            )
        )

        text = emit_wram_map(symbols)

        self.assertIn("SRAM 00 A600 sPartyMail", text)
        self.assertIn("WRAM 01 D141 wCurDamage", text)
        self.assertIn("HRAM 00 FF9F hROMBank", text)
        self.assertNotIn("BattleCommand_DamageCalc", text)

    def test_bgb_sym_parity_canonical_set(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "pokegold.sym"
            exported = root / "pokegold.bgb.sym"
            source.write_text(
                "; File generated by rgblink\n"
                "00:a600 sPartyMail\n"
                "01:d141 wCurDamage\n"
                "00:ff9f hROMBank\n"
                "03:4000 BattleCommand_DamageCalc\n",
                encoding="utf-8",
            )

            write_bgb_sym(symbols_path=source, out_path=exported)
            report = build_parity_report(symbols_path=source, bgb_symbols_path=exported)

        self.assertTrue(report["ok"], report)
        self.assertEqual(report["source_symbol_count"], 4)

    def test_bgb_sym_parity_flags_missing_symbol(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "pokegold.sym"
            exported = root / "pokegold.bgb.sym"
            source.write_text("01:d141 wCurDamage\n03:4000 BattleCommand_DamageCalc\n", encoding="utf-8")
            exported.write_text("01:D141 wCurDamage\n", encoding="utf-8")

            report = build_parity_report(symbols_path=source, bgb_symbols_path=exported)

        self.assertFalse(report["ok"])
        self.assertEqual(report["missing_symbols"], ["BattleCommand_DamageCalc"])

    def test_bgb_sym_parity_flags_address_mismatch(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "pokegold.sym"
            exported = root / "pokegold.bgb.sym"
            source.write_text("01:d141 wCurDamage\n", encoding="utf-8")
            exported.write_text("01:D142 wCurDamage\n", encoding="utf-8")

            report = build_parity_report(symbols_path=source, bgb_symbols_path=exported)

        self.assertFalse(report["ok"])
        self.assertEqual(report["mismatched_symbols"][0]["label"], "wCurDamage")

    def test_emit_scripts_run_from_command_line(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "pokegold.sym"
            bgb = root / "pokegold.bgb.sym"
            map_txt = root / "pokegold.map.txt"
            source.write_text("01:d141 wCurDamage\n00:ff9f hROMBank\n", encoding="utf-8")

            bgb_proc = subprocess.run(
                [
                    sys.executable,
                    "scripts/emit_bgb_sym.py",
                    "--symbols",
                    str(source),
                    "--out",
                    str(bgb),
                ],
                cwd=Path(__file__).resolve().parents[3],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                encoding="utf-8",
            )
            map_proc = subprocess.run(
                [
                    sys.executable,
                    "scripts/emit_wram_map.py",
                    "--symbols",
                    str(source),
                    "--out",
                    str(map_txt),
                ],
                cwd=Path(__file__).resolve().parents[3],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                encoding="utf-8",
            )

        self.assertEqual(bgb_proc.returncode, 0, bgb_proc.stderr)
        self.assertEqual(map_proc.returncode, 0, map_proc.stderr)
        self.assertIn("wrote 2 symbols", bgb_proc.stdout)
        self.assertIn("wrote 2 SRAM/WRAM/HRAM labels", map_proc.stdout)


def _write_symbols(text: str) -> Path:
    temp = TemporaryDirectory()
    path = Path(temp.name) / "test.sym"
    path.write_text(text, encoding="utf-8")
    _TEMP_DIRS.append(temp)
    return path


_TEMP_DIRS: list[TemporaryDirectory[str]] = []


if __name__ == "__main__":
    unittest.main()
